In [1]:
import numpy as np

#### Ejecicio #1:    Operaciones Matriciales
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático: 
* Computar las normas l0, l1, l2, l-infinito

* l0: número de elementos diferentes a cero en el vector

In [2]:
def norma_0(vector):
  suma = []
  for v in range(len(vector)):
    sum = 0
    for e in range(len(vector[v])):
      if (vector[v][e])!= 0:
        sum += 1
    suma.append(sum)
  return suma

In [3]:
A = np.array([[2, 3, 2],[0, 1, 2],[3, 2, 1]])

In [4]:
mod_0 = norma_0(A)
print(mod_0)

[3, 2, 3]


* l1-l2: 
    ![](https://latex.codecogs.com/svg.latex?%7B%5Ccolor%7BOrange%7D%20%5Cleft%20%5C%7C%20x%20%5Cright%20%5C%7C_%7Bp%7D%20%3D%20%5Cleft%20%28%20%5Csum_%7B1%7D%5E%7Bn%7D%20%5Cleft%20%7C%20x_%7Bi%7D%20%5Cright%20%7C%5Ep%20%5Cright%20%29%5E%7B%5Ctfrac%7B1%7D%7Bp%7D%7D%7D)

In [5]:
def norma_p(n, vector):
  suma = []
  for v in range(len(vector)):
    sum = 0
    for e in range(len(vector[v])):
      sum += (abs(vector[v][e])**n)
    sum = sum**(1/n)
    suma.append(sum)
    
  return suma

In [6]:
mod_1 = norma_p(1, A)
print(mod_1)

[7.0, 3.0, 6.0]


In [7]:
mod_2 = norma_p(2, A)
print(mod_2)

[4.123105625617661, 2.23606797749979, 3.7416573867739413]


* l-infinito:
     ![](https://latex.codecogs.com/svg.latex?%7B%5Ccolor%7BOrange%7D%20%5Cleft%20%5C%7C%20x%20%5Cright%20%5C%7C_%7B%5Cinfty%7D%20%3D%20max_%7Bi%7D%20%5Cleft%20%7C%20x_%7Bi%7D%20%5Cright%20%7C%7D)

In [8]:
def norma_inf(vector):
  max = np.amax(vector,axis=1)
  return max

#### Ejecicio #2:    Sorting :house:
Dada una matriz en formato numpy array, donde cada fila de la matriz representa un vector matemático, se requiere computar la norma l2 de cada vector.
Una vez obtenida la norma, se debe ordenar las mísmas de mayor a menor. Finalmente, obtener la matriz original ordenada por fila según la norma l2.

_Todas las operaciones debe ser vectorizadas._

In [9]:
# Defino nuevamente la matriz original

mod = norma_p(2,A)  # Vector con la norma |2|

In [10]:
Aaux = np.c_[ A, mod ] # Agrego la matriz con la norma de cada vector
Aaux

array([[2.        , 3.        , 2.        , 4.12310563],
       [0.        , 1.        , 2.        , 2.23606798],
       [3.        , 2.        , 1.        , 3.74165739]])

In [11]:
n = len(A) # Define n como la ultima columna de A
Aaux = Aaux[ Aaux[:, n].argsort()[::-1]] # Ordena la matriz por la columna n, [::-1] ordena de mayor a menor
Aaux

array([[2.        , 3.        , 2.        , 4.12310563],
       [3.        , 2.        , 1.        , 3.74165739],
       [0.        , 1.        , 2.        , 2.23606798]])

In [12]:
b = np.delete(Aaux, np.s_[-1:], axis=1) # Elimino la ultima columna y queda la matriz A ordenada segun la norma de su vector de mayor a menor
b

array([[2., 3., 2.],
       [3., 2., 1.],
       [0., 1., 2.]])

#### Ejecicio #4:    Precision, Recall, Accuracy :house:
En los problemas de clasificación, se cuenta con dos arreglos, la **verdad** (ground truth) y la **predicción** (prediction). 
Cada elemento de los arreglos puede tomar dos valores: _True_ (representado por 1) y _False_ (representado por 0). 
Por lo tanto, se pueden definir cuatro variables:
* True Positive (TP): la verdad es 1 y la predicción es 1.
* True Negative (TN): la verdad es 0 y la predicción es 0.
* False Negative (FN): la verdad es 1 y la predicción es 0.
* False Positive (FP): la verdad es 0 y la predicción es 1.

A partir de esas cuatro variables, se definen las siguientes métricas:
* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)

Para los siguientes arreglos, representando la **verdad** y la **predicción**,
calcular las métricas anteriores con operaciones vectorizadas en NumPy.
* truth = [1,1,0,1,1,1,0,0,0,1]
* prediction = [1,1,1,1,0,0,1,1,0,0]

In [21]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0]) 

In [34]:
def performance_measure(y_true, y_pred):
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    for i in range(len(y_pred)): 
        if y_true[i]==y_pred[i]==1:
           TP += 1
        if y_pred[i]==1 and y_true[i]!=y_pred[i]:
           FP += 1
        if y_true[i]==y_pred[i]==0:
           TN += 1
        if y_pred[i]==0 and y_true[i]!=y_pred[i]:
           FN += 1
    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    accuracy = (TP + TN) / (TP + TN + FP + FN)

    print(" Precision: ", precision*100,"%\n Recall: ", recall*100, "%\n Accuracy: ", accuracy*100, "%")

    return(precision, recall, accuracy, TP, FP, TN, FN)

In [35]:
performance_measure(truth, prediction)

 Precision:  50.0 %
 Recall:  50.0 %
 Accuracy:  40.0 %


(0.5, 0.5, 0.4, 3, 3, 1, 3)